### ISSUE TITLE
update conventional-commit-types dependency

### ISSUE THREAD

**Issue by skeggse** [commitizen/cz-conventional-changelog#107]
Version 3.0.0 of `conventional-commit-types` removes the `improvement` commit type. For consistency with the conventional commits spec, we'd like to see this change in the commitizen CLI, and since it's a breaking change we'd need to update the dependency here. Would this be a breaking change here, too?

cc @AndersDJohnson

**Comment by skeggse** [comment]
See #105.

**Comment by zanza00** [comment]
I have a project that has both the prompt both the lint of commit messages (using [commitlint](https://github.com/conventional-changelog/commitlint)) and when using the prompt by cz and choosing `improvement`, the lint fails which is frustrating.

I forced the v3 of `conventional-commit-types` in my package.json but that is not ideal

**Comment by AndersDJohnson** [comment]
I am not an active maintainer of this project but I support the change in #105. :+1:

**Comment by skeggse** [comment]
Closed and released in 3.0.3 per #105.
