### ISSUE TITLE
Update README with disableScopeLowerCase option

### ISSUE THREAD

**Issue by ATLSAPI** [commitizen/cz-conventional-changelog#110]
As #96 has now been merged in, should the README be updated to include information about `disableScopeLowerCase`?

I'm happy to create a PR for this 😄

**Comment by coldacid** [comment]
Yes please! I've been struggling trying to figure out how to configure this in order to try out #96 on my project.

**Comment by buzzzzx** [comment]
I am struggling to figure out how to configure this with **disableScopeLowerCase** option, too.

**Comment by buzzzzx** [comment]
Oh. I just add this into my `.czrc`

`"disableScopeLowerCase": 1`

And which works.
