### ISSUE TITLE
Consider switching to a different prompt library

### ISSUE THREAD

**Issue by GitGangGuy** [commitizen/cz-conventional-changelog#119]
Currently, [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/), the library you are using to display prompts, has a [unfixed bug that has remained silent since a year](https://github.com/SBoudrias/Inquirer.js/issues/793). This bug causes the questions to duplicate/not get overwritten/not get cleared properly anytime a key is pressed, resulting in a unbelievably awful experience.
Looking forward, I don't believe that issue will receive a lot of attention; it appears all Inquirer maintainers don't use Windows which seems to correlate to the error message.
To prove this, I tried running `cz-conventional-changelog` multiple times in different command line environments (PowerShell 6, PowerShell Core 6, PowerShell 7, Git Bash, CMD, Terminus, Hyper) and all of them (even the bash-like ones) share the same problem.
It appears to originate from calls in git hooks (in my case via husky), but also from npm script calls (in the package.json file). This leaves me and other Windows users only with either calling `git-cz` manually from the command line before we commit, without any control, or by ignoring the issue.
I'd appreciate if you could move towards a other library that also supports prompts in git hooks, since this seems like a mandatory feature to me.

**Comment by PavelZubkov** [comment]
I have same problem.

> It appears to originate from calls in git hooks (in my case via husky), but also from npm script calls (in the package.json file).

In my case i run `node index.js`. As soon as the input reaches the line break, each subsequent character entered leads to a duplication of everything.

I try install PowerShell on Ubuntu. Not reproduced, only windows

**Comment by s14k51** [comment]
@GitGangGuy @PavelZubkov What other prompt libraries have you used on windows that gave you a smooth experience?

**Comment by GitGangGuy** [comment]
I'll close this. The problem only arises for me in a git hook, which has been solved in an issue I submitted on huskys github. Thanks to everyone who joined in!
