### ISSUE TITLE
Add "content" case

### ISSUE THREAD

**Issue by pensierinmusica** [commitizen/cz-conventional-changelog#15]
Hi,

I've been using the Angular commit messages convention fro more than a year now, and I find it great. If I understand correctly, this pretty much mirrors `cz-conventional-changelog` prompts.

Imho, there's one type of commits that is very relevant though, and it's missing from the list: the "content" type.

Every time I'm working on an app or a website and I need to commit changes to its static content (e.g. text in a page, pictures, titles, etc.) I can't find a good fit in the existing commit types included in the list.

In fact, it's neither "feat", nor "style", nor "docs". Apart from this, I've found the list to be pretty exhaustive.

Therefore, I propose to include the "content" type in the list, with the description "A UI content change that only affects static text or images" (or something similar).

Please let me know your thoughts, and if you'd like me to create a PR for it.

Thanks! Cheers :)

**Comment by jimthedev** [comment]
Hi there and thanks for the suggestion. We cz-conventional-changelog follows the conventional-changelog convention, but you are free to fork it to make the changes you want. Currently the best bet is to follow these steps:

1. Fork this repository.
2. Make changes to index.js to add the new category.
3. Push your new adapter to npm under your own adapter name, say, for example cz-my-cool-adapter
4. Use commitizen init cz-my-cool-adapter --save-dev --save-exact and then adding the adapter to your package.json's config.commitizen key as shown in the docs.

**Comment by pensierinmusica** [comment]
Hi @jimthedev, thanks for the suggestion. I figured it was possible to create a modified version and use it. Still, I think the "content" case would be useful for everyone and not just for me, so it would make sense to include it in `cz-conventional-changelog`.

Can you please give me more details about the `conventional-changelog` standard and where I can propose a modification for it?

Also, the link in `readme.md` of this repo is currently broken, could you please check?

Thanks! Cheers

**Comment by jimthedev** [comment]
You can suggest changes to the convention here: https://github.com/stevemao/conventional-changelog-angular/blob/master/index.js

**Comment by jimthedev** [comment]
Good call on the readme. Link is now fixed.

**Comment by pensierinmusica** [comment]
K thanks, I've posted a proposal in that repo!
