### ISSUE TITLE
Split Breaking Changes and issues closed into two separate questions

### ISSUE THREAD

**Issue by tusharmath** [commitizen/cz-conventional-changelog#17]
The idea behind doing this is that if the user has a breaking change, you could auto prefix it with `BREAKING CHANGE` text. Often times there are typos while writing this text in all caps.

original issue: https://github.com/commitizen/cz-cli/issues/192

**Comment by markdalgleish** [comment]
@jimthedev is this something you want implemented? I'm happy to do this myself and send a PR—otherwise I'll have to maintain my own custom engine, which I'd rather avoid.

**Comment by travi** [comment]
as another consumer, i agree that this would be a helpful change

**Comment by jimthedev** [comment]
@markdalgleish @travi I would be ok with it. We're going to need to bump major versions but if you put in a PR I'd expect it to get merged. @LinusU how does this sound?

**Comment by LinusU** [comment]
👍

**Comment by wizardzloy** [comment]
@markdalgleish are you working on this? I could implement this if you don't have time

**Comment by tusharmath** [comment]
Wow Thanks a ton!
