### ISSUE TITLE
Please consider the case with new npm and flat dependencies

### ISSUE THREAD

**Issue by Den-dp** [commitizen/cz-conventional-changelog#4]
It looks like this line will brake with new npm and flat dependencies https://github.com/commitizen/cz-conventional-changelog/blob/master/index.js#L3

**Comment by jimthedev** [comment]
Good find Hmmm... Haven't played with npm v3 yet. Do you know if this can be replaced with some other path resolution method?

**Comment by Den-dp** [comment]
@jimthedev tbh I'm not quite sure what was the reason to use `relative` path, but from my point of view even this simple change should work everywhere.
```
var wrap = require('word-wrap');
```
https://nodejs.org/api/modules.html#modules_file_modules
https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders
