### ISSUE TITLE
Supporting multiline for conventional changelog

### ISSUE THREAD

**Issue by lirantal** [commitizen/cz-conventional-changelog#41]
Hi @jimthedev,

This is in follow-up to https://github.com/commitizen/cz-cli/issues/398 which I know you closed it and forwarded here which is I'm opening it in the relevant place for another discussion.

I believe that this adapter is inspired and follows Angular guideline for commits, which clearly allows multilines. Obviously it's easy to fork this adapter and make the change but it would be better IMHO to just update this adapter to work according to expected semantics for commits.

Example commit: https://github.com/angular/angular.js/commit/0694af8fc4c856f5174545450091602e51f02a11

![image](https://cloud.githubusercontent.com/assets/316371/21870092/6c6afcee-d863-11e6-97f3-1f6d71b1f22c.png)

**Comment by lirantal** [comment]
Sorry, that's my bad.
The conventional changelog does allow you to provide further "next-line" through the last question.

Closing.

**Comment by marceloavf** [comment]
How do you make it work @lirantal ?

**Comment by lirantal** [comment]
hey @marceloavf,
no magic to it, I just noted that the last 2 questions in the interactive prompt result in their own new line.

for example, the following:
![image](https://user-images.githubusercontent.com/316371/32136099-27190972-bc12-11e7-8ef0-809ae1290b38.png)

turns into:
![image](https://user-images.githubusercontent.com/316371/32136104-34e619aa-bc12-11e7-889e-e57e4bac19e9.png)
