### ISSUE TITLE
Error loading "word-wrap"

### ISSUE THREAD

**Issue by mahpah** [commitizen/cz-conventional-changelog#6]
I got this error when using version 1.1.1, everything work fine in 1.1.0. I think it should load `wordwrap/index.js` instead of `wordwrap.js`

```
Potentially unhandled rejection [3] Error: Error loading "word-wrap" at file:/.../node_modules/cz-conventional-changelog/word-wrap.js
Error loading "word-wrap" from "index" at file:/.../node_modules/cz-conventional-changelog/index.js
ENOENT: no such file or directory, open '/.../node_modules/cz-conventional-changelog/word-wrap.js'
    at Error (native)
```
```
$ node -v  
v4.1.1
```

**Comment by jccguimaraes** [comment]
Got the same problem from 1.1.1 (node v4.1.0) downgraded to 1.1.0 and working properly

**Comment by ericdouglas** [comment]
Got the same problem from 1.1.1 **and 1.1.0** (node v4.1.0), downgraded to **1.0.1** and worked properly.

**Comment by sebastienbarre** [comment]
Confirming issue for `iojs` as well. Downgraded to 1.1.0 worked.

**Comment by jimthedev** [comment]
Thank you all so much for the feedback and apologies for the inconvenience. I've confirmed that a [recent PR](https://github.com/commitizen/cz-conventional-changelog/pull/5) introduced this bug for older node versions in an attempt to support new npm and node versions. Bottom line, I am rolling back that PR and have released 1.1.2 which is effectively the same as 1.1.0. Rolling back the breaking changes.

I can't account for @ericdouglas having to go back all the way to 1.0.1 but at this point please continue to use which ever version you have working. Perhaps consider blowing away your node_modules folder or `npm cache clear`

Unfortunately npm@3 and node@4 have introduced a bunch of new functionality and breaking changes that impact commitizen. The primary mistake here is that I introduced breaking changes w/o bumping a major version. Specifically the flattening of dependencies in npm3 is a large change that breaks some of the fundamental assumptions cz could safely make in the past. We can no longer make these assumptions and unfortunately without a comprehensive test suite, it make it very hard to know exactly what the matrix of functionality looks like.

So, I have released 1.1.2 tonight. If you could all report back once you've upgraded to that, I'd appreciate it.

I would love to have the following information:

1. node version
2. npm version
3. commitizen cli version
4. if cz-conventional-changelog is working for you

Thanks so much for your patience.

**Comment by jimthedev** [comment]
One thing I will be focusing on for the commitizen 2.0 is making sure that there is a comprehensive test suite to find these kind of regressions in the future. I'll be creating a 2.0 milestone in the cz-cli repo that you can track for npm3 support.

**Comment by mahpah** [comment]
Thanks @jimthedev, v1.1.2 worked fine for me. Here the information you might need.

```
node@4.1.1
npm@2.14.4
commitizen@1.0.4
```

**Comment by dferber90** [comment]
Unfortunately it is not working for me with 1.1.2 and 1.1.0.

Report for 1.1.2:
```bash
$ git cz
Potentially unhandled rejection [3] Error: Error loading "node_modules/word-wrap/index" at file:/../eslint-plugin-meteor/node_modules/cz-conventional-changelog/node_modules/word-wrap/index.js
Error loading "node_modules/word-wrap/index" from "index" at file:/../eslint-plugin-meteor/node_modules/cz-conventional-changelog/index.js
ENOENT, open '/../eslint-plugin-meteor/node_modules/cz-conventional-changelog/node_modules/word-wrap/index.js'
    at Error (native)
```

Versions
````
node v0.12.7
npm@3.3.4
commitizen@1.0.4
```

**Comment by jimthedev** [comment]
Thanks @mahpah. 

@dferber90 I've opened an issue in the main cli project for [NPM 3 support](https://github.com/commitizen/cz-cli/issues/16). It has been added to the commitizen 2.0 milestone.

**Comment by jimthedev** [comment]
Closed. See my comment above for a new issue to track eventual NPM3 support.

**Comment by dferber90** [comment]
Thank you. I've just started using commitizen and cz-conventional-changelog yesterday. It's awesome!

**Comment by jimthedev** [comment]
@dferber90 Fantastic. Glad you're enjoying it. :+1:  :D
