### ISSUE TITLE
Issues closed by this change

### ISSUE THREAD

**Issue by rizgit** [commitizen/cz-conventional-changelog#7]
I think I have configured correctly and when I run git cz (or npm run commit following Kents lessons), and when I enter 'closes #1' for (for breaking changes or issues closed), it does not get added to commit log. Only the scope and the short message is committed to the log . My git log does not breaks into lines and does not show the issues closed. Anything I am missing?.

Date:   Wed Oct 7 11:47:27 2015 +1100
chore(releasing): showing short message only 
Date:   Wed Oct 7 11:25:37 2015 +1100
chore(releasing): add travis config conventional

**Comment by jimthedev** [comment]
Hi @rizgit. Sorry to hear that something wasn't working. 

Two things:

1. Would you mind trying to upgrade to Commitizen 2? It was just released last night and should help with some problems, including newer npm and node versions.
2. If that doesn't work, could you try to do a commit with commitizen then immediately afterwards type `git --no-pager log -1 --pretty=%B`. Then if you can copy and paste the output of that to this issue, that'd be great. Also, if you can find out your node and npm versions by doing `node -v` and `npm -v` that's probably also be useful.

Thanks!

Jim

**Comment by jimthedev** [comment]
Closing this for now but feel free to reopen if you can provide a bit more info. Thanks!
