### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kentcdodds** [commitizen/cz-conventional-changelog#8]
[This](https://github.com/commitizen/cz-conventional-changelog/commit/e98818a229bad67f9003e58d78eb5722cbbe187c) needs to be released. Do you have any problem with me doing that? I'll do it in 10 minutes if you don't respond!!! :clock11: :bomb:

**Comment by kentcdodds** [comment]
I'm confused. The latest version in master's [package.json](https://github.com/commitizen/cz-conventional-changelog/blob/master/package.json#L3) states it's version 1.1.0, but the latest version on npm is 1.1.2, and the tag on github has a package.json with 1.1.2 and was released just 2 weeks ago but doesn't have the fix in it which happened 3 weeks ago...

What kind of operation are you running here Jim!? :P

**Comment by kentcdodds** [comment]
I'll tell you what. I'll set up semantic-release and publish-latest on this repo, then everything will be better.

**Comment by kentcdodds** [comment]
Hey @jimthedev, could you add @commtizen-bot to the owners on the org and https://www.npmjs.com/~commitizen-bot to the collaborators on npm? Thanks!

**Comment by kentcdodds** [comment]
Forget about npm, I got that working. Just need to add @commitizen-bot to the org. Thanks!

**Comment by jimthedev** [comment]
Hey, sorry Kent. I've been sick on and off for the past month so I'm a bit behind and clearly missed something here. Thanks for catching it.

Here is a quick update:

- Commitizen-bot has been added on npm
- I want to implement all of the changes you talk about in your library egghead series.
- I've started a complete rewrite of cz-cli including a full test suite. It is slow going but includes the ability to run `commitizen init` which will npm install the adapter and edit package.json to include the dependency.
- The version in package.json of this adapter is obviously wrong. My guess is I missed a push.

Thanks for lending a hand. :)

**Comment by kentcdodds** [comment]
That all sounds amazingly awesome. Could you add the @commitizen-bot account to the github org so it can push tagged releases?

**Comment by jimthedev** [comment]
Invite sent!

**Comment by kentcdodds** [comment]
It was a bit bumpy, but everything's set now! @commitizen-bot is at our command :-)

**Comment by kentcdodds** [comment]
Unfortunately, I'm still getting this error when using this with angular-formly :-(

> Potentially unhandled rejection [3] Error: Error loading "word-wrap" at file:/Users/kentcdodds/Developer/formly-js/angular-formly/node_modules/cz-conventional-changelog/word-wrap.js
> Error loading "word-wrap" from "index" at file:/Users/kentcdodds/Developer/formly-js/angular-formly/node_modules/cz-conventional-changelog/index.js
> ENOENT: no such file or directory, open '/Users/kentcdodds/Developer/formly-js/angular-formly/node_modules/cz-conventional-changelog/word-wrap.js'
>     at Error (native)

No idea what's up... I'm using npm@3...

**Comment by jimthedev** [comment]
It is npm3. It moves around packages which unfortunately breaks some of the assumptions that cz makes about the filesystem. I am working on a fix that takes this into account as part of 2.0 which includes a CI test suite.

**Comment by jimthedev** [comment]
2.0 is also written in ES6 w/ Babel so you'll be right at home @kentcdodds

**Comment by kentcdodds** [comment]
Awesome! I recommend you checkout the way [add-to-path](https://github.com/kentcdodds/node-add-to-path) is built and released. Writing your stuff in ES6 is awesome, automatically building and releasing it is even cooler! Just check out [the scripts](https://github.com/kentcdodds/node-add-to-path/blob/master/package.json#L6-L16) and the [.travis.yml](https://github.com/kentcdodds/node-add-to-path/blob/master/.travis.yml#L17-L23)

**Comment by jimthedev** [comment]
Sounds good @kentcdodds. I expect it to be ready for review in the next few days or so. Once I get all of that integrated would you be willing to do a final review?

**Comment by kentcdodds** [comment]
Sure!

**Comment by jimthedev** [comment]
![high five gang](https://cloud.githubusercontent.com/assets/108938/10463702/a41cedd4-71ab-11e5-87ee-fe72e16fa232.gif)
