### ISSUE TITLE
Cannot find module 'commitizen'

### ISSUE THREAD

**Issue by travi** [commitizen/cz-conventional-changelog#89]
after the latest release, i am seeing the following error when running `git cz` the same way i always have: `Cannot find module 'commitizen'`. I [noticed the same problem](https://github.com/commitizen/cz-conventional-changelog/pull/75#issuecomment-461684823) when attempting to test [this PR](https://github.com/commitizen/cz-conventional-changelog/pull/75), but assumed at the time that I was simply pulling it down incorrectly during my attempt to test.

The simplest way to reproduce is probably to 
* clone https://github.com/travi/javascript-scaffolder
* `nvm install`
* `npm install -g commitizen` (this is v4.0.2 for me currently)
* `npm install`
* make some code change and stage it for commit
* `git cz`
* see error

i'll try to find a chance to dig a bit to see if i can understand why this is happening for me and will add comments if i find anything, but wanted to at least get this opened in case the cause might be obvious to one of the core team.

**Comment by travi** [comment]
i notice that if i install `commitizen` locally, things work again, so it seems that `git cz` is not finding the globally installed version for some reason

**Comment by travi** [comment]
looks to me like the issue is the direct dependency on the `commitizen` package in order to [use its config loader](https://github.com/commitizen/cz-conventional-changelog/blob/7234529b651b396716dfd015631f188524ee4e06/index.js#L5). This package only marks `commitizen` as a `devDependency`, so when `commitizen` is installed globally, but `cz-conventional-changelog` is installed locally, it isn't able to access `commitizen`.

i'll put up a PR to mark `commitizen` as a `dependency` instead of a `devDependency`. i could see this as a potential reason to split the config loader to a separate package, but that decision is totally in your hands.

**Comment by michaelmccallam** [comment]
@morphatic thanks for this. I got the message 'Could not resolve' after following the docs and installing  -g and also setting up the repo to be Comitizen friendly. 
I updated the package.json config as you suggested

`"config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  }`
and it now works! - this was effecting cz-cli@4.3.0, cz-conventional-changelog@3.3.0
