### ISSUE TITLE
Make lower-casing of scope optional

### ISSUE THREAD

**Issue by coldacid** [commitizen/cz-conventional-changelog#94]
Using cz-conventional-changelog with non-JS projects where components and file names may be cased is problematic due to the forced lower-casing of the value typed in for the scope prompt. Lower-casing should be optional, although defaulting to on is fine.

**Comment by rafalmaciejewski** [comment]
I need to stick with v2 until this will be available since we need those uppercase letters at the front of the subject (because of reasons) :/
It'd be great if anyone came up with a workaround for this.

**Comment by rafalmaciejewski** [comment]
there is already a pull request for this #96

**Comment by ATLSAPI** [comment]
> there is already a pull request for this #96
This PR has now merged and released in [v3.1.0](https://www.npmjs.com/package/cz-conventional-changelog/v/3.1.0). Does this need closing?

**Comment by coldacid** [comment]
@ATLSAPI let me update and try it out.

**Comment by coldacid** [comment]
Looks like this doesn't work on Windows when using a global install as Node will grab the 3.0.1 install out of commitizen itself rather than the side-installed 3.1.0 cz-conventional-changelog. :(

**Comment by coldacid** [comment]
So apart from that caveat (which is more of a Node and commitizen config issue) it looks like the functionality itself worked. Since providing an absolute path to cz-conventional-changelog in .czrc works, I'd say that this issue is good and done. Closing.
