### ISSUE TITLE
Bug, subject converted to lowercase

### ISSUE THREAD

**Issue by unlight** [commitizen/cz-conventional-changelog#97]
Function `filterSubject` converts all inputs to lower case.
I want to keep my subject sentence cased.

**Comment by bjoluc** [comment]
This is what happens:

https://github.com/commitizen/cz-conventional-changelog/blob/861b36171d9670b34b287acd7bd01db6e3238405/engine.js#L24-L34

I'd like to keep my first letter uppercase as well – @jimthedev I'm failing to find a spec for this. Am I missing something? If not, would you accept a PR to remove the modification of the first letter? Thanks in advance!

**Comment by unlight** [comment]
I switched to https://github.com/leonardoanalista/cz-customizable

**Comment by chrisgarber** [comment]
I believe this is fixed by the config option `disableSubjectLowerCase`

**Comment by bjoluc** [comment]
Absolutely, thanks @chrisgarber! @unlight Would you mind closing the issue?
